# permissions for end users to edit clusterfederatedtrustdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfederatedtrustdomain-editor-role
rules:
- apiGroups:
  - spire.spiffe.io
  resources:
  - clusterfederatedtrustdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - spire.spiffe.io
  resources:
  - clusterfederatedtrustdomains/status
  verbs:
  - get
