# permissions for end users to view clusterfederatedtrustdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterfederatedtrustdomain-viewer-role
rules:
- apiGroups:
  - spire.spiffe.io
  resources:
  - clusterfederatedtrustdomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - spire.spiffe.io
  resources:
  - clusterfederatedtrustdomains/status
  verbs:
  - get
